name: Health Triage API

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.100-rc.1.*'
      - name: Restore
        run: dotnet restore ./HealthTriageAI.ApiService/HealthTriageAI.ApiService.csproj
      - name: Build
        run: dotnet build ./HealthTriageAI.ApiService/HealthTriageAI.ApiService.csproj --configuration Release --no-restore
      - name: Publish
        run: dotnet publish ./HealthTriageAI.ApiService/HealthTriageAI.ApiService.csproj -c Release -o "${{ github.workspace }}/publish" --no-build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-publish
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: api-publish
          path: ./publish
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: HealthTriageAI-Portfolio
          package: ./publish
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_HEALTHTRIAGEAI }}
